//
//  ___FILENAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//___COPYRIGHT___
//

#include "___FILEBASENAME___.h"

___FILEBASENAMEASIDENTIFIER___::___FILEBASENAMEASIDENTIFIER___(){}
___FILEBASENAMEASIDENTIFIER___::~___FILEBASENAMEASIDENTIFIER___(){}
